{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "# openai\n",
    "# os.environ['OPENAI_API_KEY'] = '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'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "os.environ['OPENAI_API_KEY'] = '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'\n",
    "del os.environ['OPENAI_API_TYPE']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "environ({'ALLUSERSPROFILE': 'C:\\\\ProgramData', 'APPDATA': 'C:\\\\Users\\\\linjason\\\\AppData\\\\Roaming', 'CHROME_CRASHPAD_PIPE_NAME': '\\\\\\\\.\\\\pipe\\\\crashpad_17004_TNXZZPGYUVTOOTJI', 'CODEBOX_API_KEY': 'sk-d1076d106bbb02fdae10d07d3375fa1ada39546baa30d351', 'COMMONPROGRAMFILES': 'C:\\\\Program Files\\\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\\\Program Files (x86)\\\\Common Files', 'COMMONPROGRAMW6432': 'C:\\\\Program Files\\\\Common Files', 'COMPUTERNAME': 'WHOCARES', 'COMSPEC': 'C:\\\\WINDOWS\\\\system32\\\\cmd.exe', 'CONDA_DEFAULT_ENV': 'codeinterpreter', 'CONDA_EXE': 'C:\\\\Users\\\\linjason\\\\Miniconda3\\\\Scripts\\\\conda.exe', 'CONDA_PREFIX': 'c:\\\\Users\\\\linjason\\\\AppData\\\\Local\\\\anaconda3\\\\envs\\\\codeinterpreter', 'CONDA_PROMPT_MODIFIER': '(codeinterpreter) ', 'CONDA_PYTHON_EXE': 'C:\\\\Users\\\\linjason\\\\Miniconda3\\\\python.exe', 'CONDA_ROOT': 'C:\\\\Users\\\\linjason\\\\Miniconda3', 'CONDA_SHLVL': '1', 'DEPLOYMENT_NAME': 'gpt-35-turbo', 'DRIVERDATA': 'C:\\\\Windows\\\\System32\\\\Drivers\\\\DriverData', 'EFC_10904': '0', 'ELECTRON_RUN_AS_NODE': '1', 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer', 'FPS_BROWSER_USER_PROFILE_STRING': 'Default', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\\\Users\\\\linjason', 'JPY_INTERRUPT_EVENT': '2808', 'LOCALAPPDATA': 'C:\\\\Users\\\\linjason\\\\AppData\\\\Local', 'LOGONSERVER': '\\\\\\\\WHOCARES', 'NUMBER_OF_PROCESSORS': '8', 'ONEDRIVE': 'C:\\\\Users\\\\linjason\\\\OneDrive - Microsoft', 'ONEDRIVECOMMERCIAL': 'C:\\\\Users\\\\linjason\\\\OneDrive - Microsoft', 'OPENAI_API_BASE': 'https://oh-ai-openai-scu.openai.azure.com/', 'OPENAI_API_KEY': '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', 'OPENAI_API_VERSION': '2023-05-15', 'ORIGINAL_XDG_CURRENT_DESKTOP': 'undefined', 'OS': 'Windows_NT', 'PATH': 'c:\\\\Users\\\\linjason\\\\AppData\\\\Local\\\\anaconda3\\\\envs\\\\codeinterpreter;c:\\\\Users\\\\linjason\\\\AppData\\\\Local\\\\anaconda3\\\\envs\\\\codeinterpreter\\\\Library\\\\mingw-w64\\\\bin;c:\\\\Users\\\\linjason\\\\AppData\\\\Local\\\\anaconda3\\\\envs\\\\codeinterpreter\\\\Library\\\\usr\\\\bin;c:\\\\Users\\\\linjason\\\\AppData\\\\Local\\\\anaconda3\\\\envs\\\\codeinterpreter\\\\Library\\\\bin;c:\\\\Users\\\\linjason\\\\AppData\\\\Local\\\\anaconda3\\\\envs\\\\codeinterpreter\\\\Scripts;c:\\\\Users\\\\linjason\\\\AppData\\\\Local\\\\anaconda3\\\\envs\\\\codeinterpreter\\\\bin;C:\\\\Users\\\\linjason\\\\Miniconda3\\\\condabin;C:\\\\Program Files (x86)\\\\Microsoft SDKs\\\\Azure\\\\CLI2\\\\wbin;C:\\\\WINDOWS\\\\system32;C:\\\\WINDOWS;C:\\\\WINDOWS\\\\System32\\\\Wbem;C:\\\\WINDOWS\\\\System32\\\\WindowsPowerShell\\\\v1.0;C:\\\\WINDOWS\\\\System32\\\\OpenSSH;C:\\\\Program Files\\\\Microsoft SQL Server\\\\150\\\\Tools\\\\Binn;C:\\\\Program Files\\\\Microsoft SQL Server\\\\Client SDK\\\\ODBC\\\\170\\\\Tools\\\\Binn;C:\\\\Program Files\\\\dotnet;C:\\\\Program Files\\\\Docker\\\\Docker\\\\resources\\\\bin;C:\\\\Program Files\\\\Git\\\\cmd;C:\\\\Users\\\\linjason\\\\AppData\\\\Local\\\\Microsoft\\\\WindowsApps;C:\\\\Users\\\\linjason\\\\AppData\\\\Local\\\\Programs\\\\Microsoft VS Code\\\\bin;C:\\\\Users\\\\linjason\\\\AppData\\\\Local\\\\GitHubDesktop\\\\bin;C:\\\\Users\\\\linjason\\\\.dotnet\\\\tools;C:\\\\Users\\\\linjason\\\\AppData\\\\Local\\\\Programs\\\\Microsoft VS Code Insiders\\\\bin', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 140 Stepping 1, GenuineIntel', 'PROCESSOR_LEVEL': '6', 'PROCESSOR_REVISION': '8c01', 'PROGRAMDATA': 'C:\\\\ProgramData', 'PROGRAMFILES': 'C:\\\\Program Files', 'PROGRAMFILES(X86)': 'C:\\\\Program Files (x86)', 'PROGRAMW6432': 'C:\\\\Program Files', 'PROMPT': '(codeinterpreter) $P$G', 'PSMODULEPATH': 'C:\\\\Program Files\\\\WindowsPowerShell\\\\Modules;C:\\\\WINDOWS\\\\system32\\\\WindowsPowerShell\\\\v1.0\\\\Modules;C:\\\\Program Files (x86)\\\\Microsoft Azure Information Protection\\\\Powershell', 'PUBLIC': 'C:\\\\Users\\\\Public', 'PYDEVD_IPYTHON_COMPATIBLE_DEBUGGING': '1', 'PYTHONIOENCODING': 'utf-8', 'PYTHONUNBUFFERED': '1', 'PYTHONUTF8': '1', 'SESSIONNAME': 'Console', 'SSL_CERT_FILE': 'c:\\\\Users\\\\linjason\\\\AppData\\\\Local\\\\anaconda3\\\\envs\\\\codeinterpreter\\\\Library\\\\ssl\\\\cacert.pem', 'SYSTEMDRIVE': 'C:', 'SYSTEMROOT': 'C:\\\\WINDOWS', 'TEMP': 'C:\\\\Users\\\\linjason\\\\AppData\\\\Local\\\\Temp', 'TMP': 'C:\\\\Users\\\\linjason\\\\AppData\\\\Local\\\\Temp', 'UATDATA': 'C:\\\\WINDOWS\\\\CCM\\\\UATData\\\\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77', 'USERDNSDOMAIN': 'northamerica.corp.microsoft.com', 'USERDOMAIN': 'NORTHAMERICA', 'USERDOMAIN_ROAMINGPROFILE': 'NORTHAMERICA', 'USERNAME': 'linjason', 'USERPROFILE': 'C:\\\\Users\\\\linjason', 'VERBOSE': 'False', 'VSCODE_AMD_ENTRYPOINT': 'vs/workbench/api/node/extensionHostProcess', 'VSCODE_CODE_CACHE_PATH': 'C:\\\\Users\\\\linjason\\\\AppData\\\\Roaming\\\\Code - Insiders\\\\CachedData\\\\083fca132543aa91a7e1de2dc23857d70ea56dd3', 'VSCODE_CRASH_REPORTER_PROCESS_TYPE': 'extensionHost', 'VSCODE_CWD': 'C:\\\\Users\\\\linjason\\\\AppData\\\\Local\\\\Programs\\\\Microsoft VS Code Insiders', 'VSCODE_HANDLES_UNCAUGHT_ERRORS': 'true', 'VSCODE_IPC_HOOK': '\\\\\\\\.\\\\pipe\\\\5f9393d147d4cf69e172494998f0c2c1-1.82.0-insider-main-sock', 'VSCODE_L10N_BUNDLE_LOCATION': '', 'VSCODE_NLS_CONFIG': '{\"locale\":\"en-us\",\"osLocale\":\"en-us\",\"availableLanguages\":{},\"_languagePackSupport\":true}', 'VSCODE_PID': '17004', 'WINDIR': 'C:\\\\WINDOWS', 'ZES_ENABLE_SYSMAN': '1', '_CONDA_OLD_CHCP': '437', '__CONDA_OPENSLL_CERT_FILE_SET': '\"1\"', 'PYDEVD_USE_FRAME_EVAL': 'NO', 'TERM': 'xterm-color', 'CLICOLOR': '1', 'FORCE_COLOR': '1', 'CLICOLOR_FORCE': '1', 'PAGER': 'cat', 'GIT_PAGER': 'cat', 'MPLBACKEND': 'module://matplotlib_inline.backend_inline'})\n"
     ]
    }
   ],
   "source": [
    "print(os.environ)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "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\n"
     ]
    }
   ],
   "source": [
    "print(os.getenv('OPENAI_API_KEY'))\n",
    "#print(os.environ['OPENAI_API_TYPE'])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Azure openai\n",
    "os.environ['OPENAI_API_KEY'] ='4af4f76a6fc8417993842838f6081555'\n",
    "os.environ['OPENAI_API_TYPE'] ='azure'\n",
    "os.environ['OPENAI_API_VERSION'] ='2023-05-15'\n",
    "os.environ['OPENAI_API_BASE'] = 'https://oh-ai-openai-scu.openai.azure.com/'\n",
    "os.environ['DEPLOYMENT_NAME'] = 'gpt-35-turbo'\n",
    "os.environ['VERBOSE'] = 'True'\n",
    "from codeinterpreterapi import CodeInterpreterSession"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<CodeBox id=58337e47-5c09-4099-9841-a2c1eb097b3e> started!\n",
      "DEPRECATION WARNING: Use agenerate_response for async generation.\n",
      "This function will be converted to sync in the future.\n",
      "You can use generate_response_sync for now.\n",
      "\n",
      "\n",
      "\u001b[1m> Entering new AgentExecutor chain...\u001b[0m\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\linjason\\Documents\\GitHub\\codeinterpreter-api\\codeinterpreterapi\\session.py\", line 442, in agenerate_response\n",
      "    response = await self.agent_executor.arun(input=user_request.content)\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\chains\\base.py\", line 556, in arun\n",
      "    await self.acall(\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\chains\\base.py\", line 349, in acall\n",
      "    raise e\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\chains\\base.py\", line 343, in acall\n",
      "    await self._acall(inputs, run_manager=run_manager)\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\agents\\agent.py\", line 1085, in _acall\n",
      "    next_step_output = await self._atake_next_step(\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\agents\\agent.py\", line 929, in _atake_next_step\n",
      "    output = await self.agent.aplan(\n",
      "  File \"c:\\Users\\linjason\\Documents\\GitHub\\codeinterpreter-api\\codeinterpreterapi\\agents\\functions_agent.py\", line 253, in aplan\n",
      "    predicted_message = await self.llm.apredict_messages(\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\chat_models\\base.py\", line 626, in apredict_messages\n",
      "    return await self._call_async(messages, stop=_stop, **kwargs)\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\chat_models\\base.py\", line 566, in _call_async\n",
      "    result = await self.agenerate(\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\chat_models\\base.py\", line 384, in agenerate\n",
      "    raise exceptions[0]\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\chat_models\\base.py\", line 485, in _agenerate_with_cache\n",
      "    return await self._agenerate(\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\chat_models\\openai.py\", line 425, in _agenerate\n",
      "    response = await acompletion_with_retry(\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\chat_models\\openai.py\", line 92, in acompletion_with_retry\n",
      "    return await _completion_with_retry(**kwargs)\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\tenacity\\_asyncio.py\", line 88, in async_wrapped\n",
      "    return await fn(*args, **kwargs)\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\tenacity\\_asyncio.py\", line 47, in __call__\n",
      "    do = self.iter(retry_state=retry_state)\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\tenacity\\__init__.py\", line 314, in iter\n",
      "    return fut.result()\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\lib\\concurrent\\futures\\_base.py\", line 451, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\lib\\concurrent\\futures\\_base.py\", line 403, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\tenacity\\_asyncio.py\", line 50, in __call__\n",
      "    result = await fn(*args, **kwargs)\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\chat_models\\openai.py\", line 90, in _completion_with_retry\n",
      "    return await llm.client.acreate(**kwargs)\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\openai\\api_resources\\chat_completion.py\", line 45, in acreate\n",
      "    return await super().acreate(*args, **kwargs)\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\openai\\api_resources\\abstract\\engine_api_resource.py\", line 217, in acreate\n",
      "    response, _, api_key = await requestor.arequest(\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\openai\\api_requestor.py\", line 310, in arequest\n",
      "    resp, got_stream = await self._interpret_async_response(result, stream)\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\openai\\api_requestor.py\", line 645, in _interpret_async_response\n",
      "    self._interpret_response_line(\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\openai\\api_requestor.py\", line 682, in _interpret_response_line\n",
      "    raise self.handle_error_response(\n",
      "openai.error.InvalidRequestError: Unrecognized request argument supplied: functions\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "AI:  Sorry, something went while generating your response.Please try again or restart the session.\n"
     ]
    }
   ],
   "source": [
    "async with CodeInterpreterSession() as session:\n",
    "    response = await session.generate_response(\n",
    "        \"\"\"\n",
    "        Plot the relative performance of tech giants\n",
    "        (Apple, Google, Microsoft, Amazon) in 2023.\n",
    "        Use a normalized plot so we can easily compare\n",
    "        the percentage changes of each stock's price over the period.\n",
    "       \"\"\"\n",
    "       )\n",
    "    print(\"AI: \", response.content)\n",
    "    for file in response.files:\n",
    "        file.show_image()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<CodeBox id=bc539697-5c8e-42ce-b510-9e3a8f9bd5c7> started!\n",
      "DEPRECATION WARNING: Use agenerate_response for async generation.\n",
      "This function will be converted to sync in the future.\n",
      "You can use generate_response_sync for now.\n",
      "\n",
      "\n",
      "\u001b[1m> Entering new AgentExecutor chain...\u001b[0m\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\linjason\\Documents\\GitHub\\codeinterpreter-api\\codeinterpreterapi\\session.py\", line 442, in agenerate_response\n",
      "    response = await self.agent_executor.arun(input=user_request.content)\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\chains\\base.py\", line 556, in arun\n",
      "    await self.acall(\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\chains\\base.py\", line 349, in acall\n",
      "    raise e\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\chains\\base.py\", line 343, in acall\n",
      "    await self._acall(inputs, run_manager=run_manager)\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\agents\\agent.py\", line 1085, in _acall\n",
      "    next_step_output = await self._atake_next_step(\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\agents\\agent.py\", line 929, in _atake_next_step\n",
      "    output = await self.agent.aplan(\n",
      "  File \"c:\\Users\\linjason\\Documents\\GitHub\\codeinterpreter-api\\codeinterpreterapi\\agents\\functions_agent.py\", line 253, in aplan\n",
      "    predicted_message = await self.llm.apredict_messages(\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\chat_models\\base.py\", line 626, in apredict_messages\n",
      "    return await self._call_async(messages, stop=_stop, **kwargs)\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\chat_models\\base.py\", line 566, in _call_async\n",
      "    result = await self.agenerate(\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\chat_models\\base.py\", line 384, in agenerate\n",
      "    raise exceptions[0]\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\chat_models\\base.py\", line 485, in _agenerate_with_cache\n",
      "    return await self._agenerate(\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\chat_models\\openai.py\", line 425, in _agenerate\n",
      "    response = await acompletion_with_retry(\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\chat_models\\openai.py\", line 92, in acompletion_with_retry\n",
      "    return await _completion_with_retry(**kwargs)\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\tenacity\\_asyncio.py\", line 88, in async_wrapped\n",
      "    return await fn(*args, **kwargs)\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\tenacity\\_asyncio.py\", line 47, in __call__\n",
      "    do = self.iter(retry_state=retry_state)\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\tenacity\\__init__.py\", line 314, in iter\n",
      "    return fut.result()\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\lib\\concurrent\\futures\\_base.py\", line 451, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\\lib\\concurrent\\futures\\_base.py\", line 403, in __get_result\n",
      "    raise self._exception\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\tenacity\\_asyncio.py\", line 50, in __call__\n",
      "    result = await fn(*args, **kwargs)\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\langchain\\chat_models\\openai.py\", line 90, in _completion_with_retry\n",
      "    return await llm.client.acreate(**kwargs)\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\openai\\api_resources\\chat_completion.py\", line 45, in acreate\n",
      "    return await super().acreate(*args, **kwargs)\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\openai\\api_resources\\abstract\\engine_api_resource.py\", line 217, in acreate\n",
      "    response, _, api_key = await requestor.arequest(\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\openai\\api_requestor.py\", line 310, in arequest\n",
      "    resp, got_stream = await self._interpret_async_response(result, stream)\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\openai\\api_requestor.py\", line 645, in _interpret_async_response\n",
      "    self._interpret_response_line(\n",
      "  File \"C:\\Users\\linjason\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\openai\\api_requestor.py\", line 682, in _interpret_response_line\n",
      "    raise self.handle_error_response(\n",
      "openai.error.InvalidRequestError: Unrecognized request argument supplied: functions\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "AI:  Sorry, something went while generating your response.Please try again or restart the session.\n"
     ]
    }
   ],
   "source": [
    "from codeinterpreterapi import CodeInterpreterSession, File\n",
    "\n",
    "# context manager for auto start/stop of the session\n",
    "async with CodeInterpreterSession() as session:\n",
    "    # define the user request\n",
    "    user_request = \"Analyze this dataset and plot something interesting about it.\"\n",
    "    files = [\n",
    "        File.from_path(\"examples/assets/iris.csv\"),\n",
    "    ]\n",
    "    # generate the response\n",
    "    response = await session.generate_response(\n",
    "        user_request, files=files\n",
    "    )\n",
    "    # output to the user\n",
    "    print(\"AI: \", response.content)\n",
    "    for file in response.files:\n",
    "        file.show_image()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
